--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CALIOPI
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."CALIOPI" 
   (	"IDCALI" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"IDOPI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.CALIOPI
SET DEFINE OFF;
Insert into TDIGITAL.CALIOPI (IDCALI,DESCRIPCION,IDOPI) values ('1','Obra Maestra','1');
Insert into TDIGITAL.CALIOPI (IDCALI,DESCRIPCION,IDOPI) values ('2','Muy Buena','2');
Insert into TDIGITAL.CALIOPI (IDCALI,DESCRIPCION,IDOPI) values ('3','Buena','3');
Insert into TDIGITAL.CALIOPI (IDCALI,DESCRIPCION,IDOPI) values ('4','Regular','1');
Insert into TDIGITAL.CALIOPI (IDCALI,DESCRIPCION,IDOPI) values ('5','Mala','2');
--------------------------------------------------------
--  DDL for Index CALIOPI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."CALIOPI_PK" ON "TDIGITAL"."CALIOPI" ("IDCALI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CALIOPI
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."CALIOPI" ADD CONSTRAINT "CALIOPI_PK" PRIMARY KEY ("IDCALI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."CALIOPI" MODIFY ("IDOPI" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."CALIOPI" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."CALIOPI" MODIFY ("IDCALI" NOT NULL ENABLE);
