--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CINE
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."CINE" 
   (	"IDCINE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"TELEFONO" NUMBER(*,0), 
	"IDPELI" NUMBER(*,0), 
	"SALA_IDSALA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.CINE
SET DEFINE OFF;
Insert into TDIGITAL.CINE (IDCINE,NOMBRE,DIRECCION,TELEFONO,IDPELI,SALA_IDSALA) values ('1','Hoys','La habana#34','29874563','1','1');
Insert into TDIGITAL.CINE (IDCINE,NOMBRE,DIRECCION,TELEFONO,IDPELI,SALA_IDSALA) values ('2','Monopolis','La esquina #32','56982260','2','2');
Insert into TDIGITAL.CINE (IDCINE,NOMBRE,DIRECCION,TELEFONO,IDPELI,SALA_IDSALA) values ('3','Maxs','La luna Azul#67','2988855','3','3');
--------------------------------------------------------
--  DDL for Index CINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."CINE_PK" ON "TDIGITAL"."CINE" ("IDCINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CINE
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."CINE" ADD CONSTRAINT "CINE_PK" PRIMARY KEY ("IDCINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."CINE" MODIFY ("SALA_IDSALA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."CINE" MODIFY ("IDPELI" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."CINE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."CINE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."CINE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."CINE" MODIFY ("IDCINE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CINE
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."CINE" ADD CONSTRAINT "CINE_SALA_FK" FOREIGN KEY ("SALA_IDSALA")
	  REFERENCES "TDIGITAL"."SALA" ("IDSALA") ENABLE;
