--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FUNCION
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."FUNCION" 
   (	"IDFUNCION" NUMBER(*,0), 
	"IDPELICULA" NUMBER(*,0), 
	"DIASEMANA" VARCHAR2(10 BYTE), 
	"HORACOM" DATE, 
	"IDSALA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.FUNCION
SET DEFINE OFF;
Insert into TDIGITAL.FUNCION (IDFUNCION,IDPELICULA,DIASEMANA,HORACOM,IDSALA) values ('1','1','Lunes',to_date('20/05/20','DD/MM/RR'),'1');
Insert into TDIGITAL.FUNCION (IDFUNCION,IDPELICULA,DIASEMANA,HORACOM,IDSALA) values ('2','2','Martes',to_date('10/06/20','DD/MM/RR'),'2');
Insert into TDIGITAL.FUNCION (IDFUNCION,IDPELICULA,DIASEMANA,HORACOM,IDSALA) values ('3','3','Sábado',to_date('25/07/20','DD/MM/RR'),'3');
Insert into TDIGITAL.FUNCION (IDFUNCION,IDPELICULA,DIASEMANA,HORACOM,IDSALA) values ('4','1','Domingo',to_date('20/05/20','DD/MM/RR'),'4');
--------------------------------------------------------
--  DDL for Index FUNCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."FUNCION_PK" ON "TDIGITAL"."FUNCION" ("IDFUNCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FUNCION
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."FUNCION" ADD CONSTRAINT "FUNCION_PK" PRIMARY KEY ("IDFUNCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("IDSALA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("HORACOM" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("DIASEMANA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("IDPELICULA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."FUNCION" MODIFY ("IDFUNCION" NOT NULL ENABLE);
