--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OPINION
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."OPINION" 
   (	"IDOPINI" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"EDAD" NUMBER(*,0), 
	"FECHA" DATE, 
	"CALIF" NUMBER(*,0), 
	"COMENT" CLOB, 
	"PELICULA_ID_PELICULA" NUMBER(*,0), 
	"IDPELI" NUMBER(*,0), 
	"CALIOPI_IDCALI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("COMENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into TDIGITAL.OPINION
SET DEFINE OFF;
Insert into TDIGITAL.OPINION (IDOPINI,NOMBRE,EDAD,FECHA,CALIF,PELICULA_ID_PELICULA,IDPELI,CALIOPI_IDCALI) values ('1','Juan Silva','55',to_date('20/04/20','DD/MM/RR'),'1','1','1','1');
Insert into TDIGITAL.OPINION (IDOPINI,NOMBRE,EDAD,FECHA,CALIF,PELICULA_ID_PELICULA,IDPELI,CALIOPI_IDCALI) values ('2','Sonia Paz','20',to_date('22/05/20','DD/MM/RR'),'2','2','2','2');
Insert into TDIGITAL.OPINION (IDOPINI,NOMBRE,EDAD,FECHA,CALIF,PELICULA_ID_PELICULA,IDPELI,CALIOPI_IDCALI) values ('3','Eduardo Castillo','30',to_date('20/08/20','DD/MM/RR'),'3','3','3','3');
--------------------------------------------------------
--  DDL for Index OPINION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."OPINION_PK" ON "TDIGITAL"."OPINION" ("IDOPINI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table OPINION
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."OPINION" ADD CONSTRAINT "OPINION_PK" PRIMARY KEY ("IDOPINI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("CALIOPI_IDCALI" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("IDPELI" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("PELICULA_ID_PELICULA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("COMENT" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("CALIF" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("EDAD" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."OPINION" MODIFY ("IDOPINI" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OPINION
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."OPINION" ADD CONSTRAINT "OPINION_CALIOPI_FK" FOREIGN KEY ("CALIOPI_IDCALI")
	  REFERENCES "TDIGITAL"."CALIOPI" ("IDCALI") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TDIGITAL"."OPINION" ADD CONSTRAINT "OPINION_PELICULA_FK" FOREIGN KEY ("PELICULA_ID_PELICULA")
	  REFERENCES "TDIGITAL"."PELICULA" ("ID_PELICULA") ON DELETE CASCADE ENABLE;
