--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PECI
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."PECI" 
   (	"PELICULA_ID_PELICULA" NUMBER(*,0), 
	"CINE_IDCINE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.PECI
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PECI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."PECI_PK" ON "TDIGITAL"."PECI" ("PELICULA_ID_PELICULA", "CINE_IDCINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PECI
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."PECI" ADD CONSTRAINT "PECI_PK" PRIMARY KEY ("PELICULA_ID_PELICULA", "CINE_IDCINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."PECI" MODIFY ("CINE_IDCINE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."PECI" MODIFY ("PELICULA_ID_PELICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PECI
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."PECI" ADD CONSTRAINT "PECI_CINE_FK" FOREIGN KEY ("CINE_IDCINE")
	  REFERENCES "TDIGITAL"."CINE" ("IDCINE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TDIGITAL"."PECI" ADD CONSTRAINT "PECI_PELICULA_FK" FOREIGN KEY ("PELICULA_ID_PELICULA")
	  REFERENCES "TDIGITAL"."PELICULA" ("ID_PELICULA") ON DELETE CASCADE ENABLE;
