--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PESALA
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."PESALA" 
   (	"PELICULA_ID_PELICULA" NUMBER(*,0), 
	"SALA_IDSALA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.PESALA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PESALA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."PESALA_PK" ON "TDIGITAL"."PESALA" ("PELICULA_ID_PELICULA", "SALA_IDSALA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PESALA
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."PESALA" ADD CONSTRAINT "PESALA_PK" PRIMARY KEY ("PELICULA_ID_PELICULA", "SALA_IDSALA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."PESALA" MODIFY ("SALA_IDSALA" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."PESALA" MODIFY ("PELICULA_ID_PELICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PESALA
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."PESALA" ADD CONSTRAINT "PESALA_PELICULA_FK" FOREIGN KEY ("PELICULA_ID_PELICULA")
	  REFERENCES "TDIGITAL"."PELICULA" ("ID_PELICULA") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TDIGITAL"."PESALA" ADD CONSTRAINT "PESALA_SALA_FK" FOREIGN KEY ("SALA_IDSALA")
	  REFERENCES "TDIGITAL"."SALA" ("IDSALA") ON DELETE CASCADE ENABLE;
