--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPARTO
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."REPARTO" 
   (	"IDPELI" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"NACIO" VARCHAR2(30 BYTE), 
	"CANTPELI" NUMBER(*,0), 
	"ESACTOR" CHAR(1 BYTE), 
	"ESDIREC" CHAR(1 BYTE), 
	"REPARTO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.REPARTO
SET DEFINE OFF;
Insert into TDIGITAL.REPARTO (IDPELI,NOMBRE,NACIO,CANTPELI,ESACTOR,ESDIREC,REPARTO_ID) values ('1','Daniela Vega','3 de Junio 1989','5','S','N','1');
Insert into TDIGITAL.REPARTO (IDPELI,NOMBRE,NACIO,CANTPELI,ESACTOR,ESDIREC,REPARTO_ID) values ('1','Aline Küppenheim ','10 de Agosto 1969','3','S','N','3');
Insert into TDIGITAL.REPARTO (IDPELI,NOMBRE,NACIO,CANTPELI,ESACTOR,ESDIREC,REPARTO_ID) values ('1','Francisco Reyes','6 de Julio 1954','3','S','N','2');
--------------------------------------------------------
--  DDL for Index REPARTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."REPARTO_PK" ON "TDIGITAL"."REPARTO" ("REPARTO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger REPARTO_REPARTO_ID_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TDIGITAL"."REPARTO_REPARTO_ID_TRG" BEFORE
    INSERT ON reparto
    FOR EACH ROW
     WHEN ( new.reparto_id IS NULL ) BEGIN
    :new.reparto_id := reparto_reparto_id_seq.nextval;
END;

/
ALTER TRIGGER "TDIGITAL"."REPARTO_REPARTO_ID_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table REPARTO
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."REPARTO" ADD CONSTRAINT "REPARTO_PK" PRIMARY KEY ("REPARTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."REPARTO" MODIFY ("REPARTO_ID" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."REPARTO" MODIFY ("ESDIREC" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."REPARTO" MODIFY ("ESACTOR" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."REPARTO" MODIFY ("CANTPELI" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."REPARTO" MODIFY ("NACIO" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."REPARTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."REPARTO" MODIFY ("IDPELI" NOT NULL ENABLE);
