--------------------------------------------------------
-- Archivo creado  - viernes-julio-10-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SALA
--------------------------------------------------------

  CREATE TABLE "TDIGITAL"."SALA" 
   (	"IDSALA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"CANTBUT" NUMBER(*,0), 
	"IDCINE" NUMBER(*,0), 
	"IDPELI" NUMBER(*,0), 
	"FUNCION_IDFUNCION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TDIGITAL.SALA
SET DEFINE OFF;
Insert into TDIGITAL.SALA (IDSALA,NOMBRE,CANTBUT,IDCINE,IDPELI,FUNCION_IDFUNCION) values ('1','Super','80','1','1','1');
Insert into TDIGITAL.SALA (IDSALA,NOMBRE,CANTBUT,IDCINE,IDPELI,FUNCION_IDFUNCION) values ('2','Premiun','60','2','2','2');
Insert into TDIGITAL.SALA (IDSALA,NOMBRE,CANTBUT,IDCINE,IDPELI,FUNCION_IDFUNCION) values ('3','Ultra','55','3','3','3');
Insert into TDIGITAL.SALA (IDSALA,NOMBRE,CANTBUT,IDCINE,IDPELI,FUNCION_IDFUNCION) values ('4','BLACK','80','1','1','1');
Insert into TDIGITAL.SALA (IDSALA,NOMBRE,CANTBUT,IDCINE,IDPELI,FUNCION_IDFUNCION) values ('5','Super Efectos','60','1','2','2');
Insert into TDIGITAL.SALA (IDSALA,NOMBRE,CANTBUT,IDCINE,IDPELI,FUNCION_IDFUNCION) values ('6','Zoom','55','1','3','3');
--------------------------------------------------------
--  DDL for Index SALA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TDIGITAL"."SALA_PK" ON "TDIGITAL"."SALA" ("IDSALA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SALA
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."SALA" ADD CONSTRAINT "SALA_PK" PRIMARY KEY ("IDSALA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TDIGITAL"."SALA" MODIFY ("FUNCION_IDFUNCION" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."SALA" MODIFY ("IDPELI" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."SALA" MODIFY ("IDCINE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."SALA" MODIFY ("CANTBUT" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."SALA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "TDIGITAL"."SALA" MODIFY ("IDSALA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SALA
--------------------------------------------------------

  ALTER TABLE "TDIGITAL"."SALA" ADD CONSTRAINT "SALA_FUNCION_FK" FOREIGN KEY ("FUNCION_IDFUNCION")
	  REFERENCES "TDIGITAL"."FUNCION" ("IDFUNCION") ON DELETE CASCADE ENABLE;
